version: '3.8'

services:
  auth-service:
    build: ./backend/services/auth-service
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    networks:
      - stockpilot-network

  inventory-service:
    build: ./backend/services/inventory-service
    ports:
      - "5002:5002"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    networks:
      - stockpilot-network

  order-service:
    build: ./backend/services/order-service
    ports:
      - "5003:5003"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    networks:
      - stockpilot-network

  report-service:
    build: ./backend/services/report-service
    ports:
      - "5004:5004"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    networks:
      - stockpilot-network

  notification-service:
    build: ./backend/services/notification-service
    ports:
      - "5005:5005"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    networks:
      - stockpilot-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
    networks:
      - stockpilot-network

networks:
  stockpilot-network:
    driver: bridge